[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes', 'tpope/vim-fugitive']
hook_add = '''
  let g:airline_theme = 'light'
  set ambiwidth=double " Powerline系フォントを利用する
  set laststatus=2
  let g:airline_powerline_fonts = 1
  let g:airline#extensions#tabline#enabled = 1
  let g:airline#extensions#tabline#buffer_idx_mode = 1
  let g:airline#extensions#whitespace#mixed_indent_algo = 1
  let g:airline_theme = 'papercolor'
  if !exists('g:airline_symbols')
    let g:airline_symbols = {}
  endif
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'jonathanfilip/vim-lucius'

[[plugins]]
repo = 'MetalPhaeton/easybracket-vim'

#[[plugins]]
#repo = 'nathanaelkane/vim-indent-guides'
#hook_add = 'let g:indent_guides_enable_on_vim_startup = 1'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'severin-lemaignan/vim-minimap'

[[plugins]]
repo = 'ryanoasis/vim-devicons'
